
# This is a basic workflow to help you get started with Actions
name: armTemplateDeployment

# Controls when the workflow will run
on: 
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel


  
jobs:
  # This workflow contains a single job called "armDeplo"
  armDeployStaging:
    name: Deploy to Staging
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      resource_group_name: stg-pluralsight-tst-rg
      location: westeurope
    environment:
      name: staging

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Login to Azure CLI
      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy the ARM template for the resource group using deploy arm action
      - name: Deploy Resource Group
        uses: Azure/arm-deploy@v1
        with:
          scope: subscription
          subscriptionId: 79e4eefb-1e09-45c9-b0e7-0860842835dd
          region: "${{env.location}}"
          template: ./arm-templates/resourcegroup.json
          parameters: 
            resourceGroupName=${{env.resource_group_name}}
            location="${{env.location}}"
          deploymentName: pstg-luralsight-tests

      # Deploy the ARM template for the storage account using deploy arm action
      - name: Deploy Storage Account
        uses: Azure/arm-deploy@v1
        id: storageAccountDeploy
        with:
          scope: resourcegroup
          resourceGroupName: ${{env.resource_group_name}}
          region: "${{env.location}}"
          template: ./arm-templates/storageaccount.json
          parameters: 
            storageAccountSku=Standard_LRS
            storageAccountName=stgv2globalbosg0028
            location=eastus
          deploymentName: stg-pluralsight-tests-storageaccount

      # Deploy the ARM template for the virtual machine in vm.json
      - name: Deploy Virtual Machine
        uses: Azure/arm-deploy@v1
        id: vmDeploy
        with:
          scope: resourcegroup
          resourceGroupName: ${{env.resource_group_name}}
          region: "${{env.location}}"
          template: ./arm-templates/vm.json
          parameters: 
            adminPassword=${{secrets.UBUNTU_ADMIN_PASSWORD}}
            location="${{env.location}}"
          deploymentName: stg-pluralsight-tests-vm

  armDeployProduction:
    name: Deploy to Production
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      resource_group_name: prod-pluralsight-tst-rg
      location: Australia Central
    environment:
      name: production

    needs: armDeployStaging

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Login to Azure CLI
      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy the ARM template for the resource group using deploy arm action
      - name: Deploy Resource Group
        uses: Azure/arm-deploy@v1
        with:
          scope: subscription
          subscriptionId: 79e4eefb-1e09-45c9-b0e7-0860842835dd
          region: "${{env.location}}"
          template: ./arm-templates/resourcegroup.json
          parameters: 
            resourceGroupName=${{env.resource_group_name}}
            location="${{env.location}}"
          deploymentName: prod-pluralsight-tests

      # Deploy the ARM template for the storage account using deploy arm action
      - name: Deploy Storage Account
        uses: Azure/arm-deploy@v1
        id: storageAccountDeploy
        with:
          scope: resourcegroup
          resourceGroupName: ${{env.resource_group_name}}
          region: "${{env.location}}"
          template: ./arm-templates/storageaccount.json
          parameters: 
            storageAccountSku=Standard_LRS
            storageAccountName=prodv2globalbosg0028
            location=eastus
          deploymentName: prod-pluralsight-tests-storageaccount

      # Deploy the ARM template for the virtual machine in vm.json
      - name: Deploy Virtual Machine
        uses: Azure/arm-deploy@v1
        id: vmDeploy
        with:
          scope: resourcegroup
          resourceGroupName: ${{env.resource_group_name}}
          region: "${{env.location}}"
          template: ./arm-templates/vm.json
          parameters: 
            adminPassword=${{secrets.UBUNTU_ADMIN_PASSWORD}}
            location="${{env.location}}"
          deploymentName: prod-pluralsight-tests-vm